"use client"

import { useCallback, useEffect, useRef, useState } from "react"
import { usePathname, useRouter } from "next/navigation"
import ReactMarkdown from "react-markdown"

interface PagefindSubResult {
  url: string
  title: string
  excerpt: string
}

interface PagefindResultData {
  url: string
  excerpt: string
  meta?: { title?: string }
  sub_results?: PagefindSubResult[]
}

interface PagefindResult {
  id: string
  data: () => Promise<PagefindResultData>
}

interface Pagefind {
  options: (options: Record<string, unknown>) => Promise<void>
  debouncedSearch: (
    query: string,
  ) => Promise<{ results: PagefindResult[] } | null>
}

interface SearchHit {
  id: string
  url: string
  title: string
  excerpt: string
}

let pagefindPromise: Promise<Pagefind | null> | null = null

async function loadPagefind(): Promise<Pagefind | null> {
  pagefindPromise ??= (async () => {
    try {
      const pagefind: Pagefind = await import(
        /* webpackIgnore: true */
        /* turbopackIgnore: true */
        // @ts-expect-error -- runtime asset generated by the pagefind build step
        "/_pagefind/pagefind.js"
      )
      await pagefind.options({ baseUrl: "/" })
      return pagefind
    } catch {
      // Index is only generated by `npm run build`; fall back to AI-only search.
      return null
    }
  })()
  return pagefindPromise
}

/** Pagefind indexes prerendered HTML under `.next`, so raw result URLs look
 * like `/server/app/book.html`; map them back to live routes. */
function normalizePagefindUrl(rawUrl: string): string {
  const url = rawUrl
    .replace(/^\/server\/app/, "")
    .replace(/\.html(#|$)/, "$1")
    .replace(/\/index(#|$)/, "/$1")
  return url.startsWith("/") ? url : `/${url}`
}

function AiSearchGlyph({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden
    >
      <path
        d="M17.89 9.78 A7 7 0 1 1 12.22 4.11"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
      <path
        d="M16.1 16.1 L20.7 20.7"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
      <path
        d="M17.6 1.6 C18 3.3 18.9 4.2 20.6 4.6 C18.9 5 18 5.9 17.6 7.6 C17.2 5.9 16.3 5 14.6 4.6 C16.3 4.2 17.2 3.3 17.6 1.6 Z"
        fill="currentColor"
      />
    </svg>
  )
}

type AnswerStatus = "idle" | "streaming" | "done" | "error"

export function AiSearch({ onOpenChange }: { onOpenChange?: (open: boolean) => void }) {
  const [isOpen, setIsOpen] = useState(false)
  const [query, setQuery] = useState("")
  const [hits, setHits] = useState<SearchHit[]>([])
  const [hasIndex, setHasIndex] = useState(true)
  const [answer, setAnswer] = useState("")
  const [answerStatus, setAnswerStatus] = useState<AnswerStatus>("idle")
  const [askedQuery, setAskedQuery] = useState("")
  const [activeIndex, setActiveIndex] = useState(0)

  const inputRef = useRef<HTMLInputElement>(null)
  const rootRef = useRef<HTMLDivElement>(null)
  const abortRef = useRef<AbortController | null>(null)
  const searchSeqRef = useRef(0)

  const router = useRouter()
  const pathname = usePathname()

  const resetAnswer = useCallback(() => {
    abortRef.current?.abort()
    abortRef.current = null
    setAnswer("")
    setAskedQuery("")
    setAnswerStatus("idle")
  }, [])

  const close = useCallback(() => {
    setIsOpen(false)
    setQuery("")
    setHits([])
    setActiveIndex(0)
    resetAnswer()
    onOpenChange?.(false)
  }, [onOpenChange, resetAnswer])

  const open = useCallback(() => {
    setIsOpen(true)
    onOpenChange?.(true)
  }, [onOpenChange])

  // Close when navigating to another page.
  useEffect(() => {
    close()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname])

  useEffect(() => {
    if (isOpen) inputRef.current?.focus()
  }, [isOpen])

  // Close on Escape and on click outside.
  useEffect(() => {
    if (!isOpen) return
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") close()
    }
    const onPointerDown = (event: MouseEvent) => {
      if (rootRef.current && !rootRef.current.contains(event.target as Node)) {
        close()
      }
    }
    document.addEventListener("keydown", onKeyDown)
    document.addEventListener("mousedown", onPointerDown)
    return () => {
      document.removeEventListener("keydown", onKeyDown)
      document.removeEventListener("mousedown", onPointerDown)
    }
  }, [isOpen, close])

  // Full-text search as the visitor types.
  useEffect(() => {
    if (!isOpen) return
    const trimmed = query.trim()
    const seq = ++searchSeqRef.current
    if (!trimmed) {
      setHits([])
      setActiveIndex(0)
      return
    }
    ;(async () => {
      const pagefind = await loadPagefind()
      if (seq !== searchSeqRef.current) return
      if (!pagefind) {
        setHasIndex(false)
        return
      }
      const response = await pagefind.debouncedSearch(trimmed)
      if (!response || seq !== searchSeqRef.current) return
      const data = await Promise.all(
        response.results.slice(0, 6).map((result) => result.data()),
      )
      if (seq !== searchSeqRef.current) return
      setHits(
        data.map((item, index) => ({
          id: `${index}-${item.url}`,
          url: normalizePagefindUrl(item.url),
          title: item.meta?.title || item.url,
          excerpt: item.excerpt,
        })),
      )
      setActiveIndex(0)
    })()
  }, [query, isOpen])

  const askAi = useCallback(async () => {
    const trimmed = query.trim()
    if (!trimmed || answerStatus === "streaming") return
    abortRef.current?.abort()
    const controller = new AbortController()
    abortRef.current = controller
    setAskedQuery(trimmed)
    setAnswer("")
    setAnswerStatus("streaming")
    try {
      const response = await fetch("/api/ai-search", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query: trimmed }),
        signal: controller.signal,
      })
      if (!response.ok || !response.body) {
        throw new Error(`Request failed with status ${response.status}`)
      }
      const reader = response.body.getReader()
      const decoder = new TextDecoder()
      let text = ""
      for (;;) {
        const { done, value } = await reader.read()
        if (done) break
        text += decoder.decode(value, { stream: true })
        setAnswer(text)
      }
      setAnswerStatus("done")
    } catch (error) {
      if ((error as Error).name === "AbortError") return
      setAnswerStatus("error")
    }
  }, [query, answerStatus])

  const alreadyAsked = answerStatus !== "idle" && askedQuery === query.trim()
  const items = query.trim()
    ? [
        ...(alreadyAsked ? [] : [{ kind: "ask" as const }]),
        ...hits.map((hit) => ({ kind: "hit" as const, hit })),
      ]
    : []

  const onInputKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      if (items.length === 0) return
      event.preventDefault()
      const delta = event.key === "ArrowDown" ? 1 : -1
      setActiveIndex((index) => (index + delta + items.length) % items.length)
      return
    }
    if (event.key === "Enter") {
      const item = items[activeIndex]
      if (!item) return
      event.preventDefault()
      if (item.kind === "ask") {
        askAi()
      } else {
        router.push(item.hit.url)
      }
    }
  }

  const showPanel = isOpen && (items.length > 0 || answerStatus !== "idle")

  return (
    <div ref={rootRef} className="ai-search-root" data-open={isOpen || undefined}>
      <button
        type="button"
        className="ai-search-trigger"
        aria-label="Search with AI"
        aria-expanded={isOpen}
        onClick={() => (isOpen ? close() : open())}
      >
        <AiSearchGlyph className="ai-search-glyph" />
      </button>

      {isOpen ? (
        <div className="ai-search-bar" role="search">
          <AiSearchGlyph className="ai-search-glyph ai-search-bar-glyph" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(event) => {
              setQuery(event.target.value)
              resetAnswer()
            }}
            onKeyDown={onInputKeyDown}
            placeholder="Search or ask anything about Tiles"
            aria-label="Search or ask anything about Tiles"
            autoComplete="off"
            autoCorrect="off"
            spellCheck={false}
            className="ai-search-input"
          />
          <button
            type="button"
            className="ai-search-close"
            aria-label="Close search"
            onClick={close}
          >
            <svg viewBox="0 0 24 24" fill="none" className="ai-search-close-glyph" aria-hidden>
              <path
                d="M6 6 L18 18 M18 6 L6 18"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
              />
            </svg>
          </button>
          <span className="ai-search-hairline" aria-hidden />
        </div>
      ) : null}

      {showPanel ? (
        <div className="ai-search-panel">
          {answerStatus !== "idle" ? (
            <div className="ai-search-answer">
              <div className="ai-search-answer-label">
                <AiSearchGlyph className="ai-search-glyph ai-search-answer-glyph" />
                <span>{askedQuery}</span>
              </div>
              {answerStatus === "error" ? (
                <p className="ai-search-answer-note">
                  Something went wrong. Please try again.
                </p>
              ) : (
                <div className="ai-search-answer-body">
                  {answer ? (
                    <ReactMarkdown>{answer}</ReactMarkdown>
                  ) : (
                    <p className="ai-search-answer-note">Thinking…</p>
                  )}
                </div>
              )}
            </div>
          ) : null}

          {items.length > 0 ? (
            <ul className="ai-search-results" role="listbox" aria-label="Search results">
              {items.map((item, index) => {
                const isActive = index === activeIndex
                if (item.kind === "ask") {
                  return (
                    <li key="ask" role="option" aria-selected={isActive}>
                      <button
                        type="button"
                        className="ai-search-item ai-search-ask"
                        data-active={isActive || undefined}
                        onMouseEnter={() => setActiveIndex(index)}
                        onClick={askAi}
                      >
                        <AiSearchGlyph className="ai-search-glyph ai-search-item-glyph" />
                        <span className="ai-search-ask-text">
                          Ask AI about “{query.trim()}”
                        </span>
                        <kbd className="ai-search-kbd">↵</kbd>
                      </button>
                    </li>
                  )
                }
                return (
                  <li key={item.hit.id} role="option" aria-selected={isActive}>
                    <button
                      type="button"
                      className="ai-search-item"
                      data-active={isActive || undefined}
                      onMouseEnter={() => setActiveIndex(index)}
                      onClick={() => router.push(item.hit.url)}
                    >
                      <span className="ai-search-hit-title">{item.hit.title}</span>
                      <span
                        className="ai-search-hit-excerpt"
                        dangerouslySetInnerHTML={{ __html: item.hit.excerpt }}
                      />
                    </button>
                  </li>
                )
              })}
            </ul>
          ) : null}

          {query.trim() && hits.length === 0 && hasIndex ? (
            <p className="ai-search-empty">No matching pages yet. Ask AI instead.</p>
          ) : null}
        </div>
      ) : null}
    </div>
  )
}
