"use client"

import { useCallback, useEffect, useMemo, useRef, useState } from "react"
import Link from "next/link"
import { usePathname, useRouter } from "next/navigation"
import ReactMarkdown from "react-markdown"

interface PagefindSubResult {
  url: string
  title: string
  excerpt: string
}

interface PagefindResultData {
  url: string
  excerpt: string
  meta?: { title?: string }
  sub_results?: PagefindSubResult[]
}

interface PagefindResult {
  id: string
  data: () => Promise<PagefindResultData>
}

interface Pagefind {
  options: (options: Record<string, unknown>) => Promise<void>
  debouncedSearch: (
    query: string,
  ) => Promise<{ results: PagefindResult[] } | null>
}

interface SearchHit {
  id: string
  url: string
  title: string
  excerpt: string
}

let pagefindPromise: Promise<Pagefind | null> | null = null

async function loadPagefind(): Promise<Pagefind | null> {
  pagefindPromise ??= (async () => {
    try {
      const pagefind: Pagefind = await import(
        /* webpackIgnore: true */
        /* turbopackIgnore: true */
        // @ts-expect-error -- runtime asset generated by the pagefind build step
        "/_pagefind/pagefind.js"
      )
      await pagefind.options({ baseUrl: "/" })
      return pagefind
    } catch {
      // Index is only generated by `npm run build`; fall back to AI-only search.
      return null
    }
  })()
  return pagefindPromise
}

/** Pagefind indexes prerendered HTML under `.next`, so raw result URLs look
 * like `/server/app/book.html`; map them back to live routes. */
function normalizePagefindUrl(rawUrl: string): string {
  const url = rawUrl
    .replace(/^\/server\/app/, "")
    .replace(/\.html(#|$)/, "$1")
    .replace(/\/index(#|$)/, "/$1")
  return url.startsWith("/") ? url : `/${url}`
}

/** The anchored section of the page that matches the query hardest, so a
 * click can land on that section instead of the top of the page. */
function pickAnchoredSubResult(
  item: PagefindResultData,
): PagefindSubResult | null {
  const countMarks = (excerpt: string) => excerpt.split("<mark>").length - 1
  let best: PagefindSubResult | null = null
  for (const sub of item.sub_results ?? []) {
    if (!sub.url.includes("#")) continue
    if (!best || countMarks(sub.excerpt) > countMarks(best.excerpt)) best = sub
  }
  return best
}

function AiSearchGlyph({ className }: { className?: string }) {
  return (
    <svg
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
      className={className}
      aria-hidden
    >
      <path
        d="M17.89 9.78 A7 7 0 1 1 12.22 4.11"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
      <path
        d="M16.1 16.1 L20.7 20.7"
        stroke="currentColor"
        strokeWidth="1.8"
        strokeLinecap="round"
      />
      <path
        d="M17.6 1.6 C18 3.3 18.9 4.2 20.6 4.6 C18.9 5 18 5.9 17.6 7.6 C17.2 5.9 16.3 5 14.6 4.6 C16.3 4.2 17.2 3.3 17.6 1.6 Z"
        fill="currentColor"
      />
    </svg>
  )
}

type AnswerStatus = "idle" | "streaming" | "done" | "error" | "unconfigured"

export function AiSearch({ onOpenChange }: { onOpenChange?: (open: boolean) => void }) {
  const [isOpen, setIsOpen] = useState(false)
  const [query, setQuery] = useState("")
  const [hits, setHits] = useState<SearchHit[]>([])
  const [hasIndex, setHasIndex] = useState(true)
  const [answer, setAnswer] = useState("")
  const [answerStatus, setAnswerStatus] = useState<AnswerStatus>("idle")
  const [askedQuery, setAskedQuery] = useState("")
  const [activeIndex, setActiveIndex] = useState(-1)
  const [shortcutLabel, setShortcutLabel] = useState<string | null>(null)

  const inputRef = useRef<HTMLInputElement>(null)
  const rootRef = useRef<HTMLDivElement>(null)
  const abortRef = useRef<AbortController | null>(null)
  const searchSeqRef = useRef(0)

  const router = useRouter()
  const pathname = usePathname()

  const resetAnswer = useCallback(() => {
    abortRef.current?.abort()
    abortRef.current = null
    setAnswer("")
    setAskedQuery("")
    setAnswerStatus("idle")
  }, [])

  const close = useCallback(() => {
    setIsOpen(false)
    setQuery("")
    setHits([])
    setActiveIndex(-1)
    resetAnswer()
    onOpenChange?.(false)
  }, [onOpenChange, resetAnswer])

  const open = useCallback(() => {
    setIsOpen(true)
    onOpenChange?.(true)
  }, [onOpenChange])

  // Close when navigating to another page.
  useEffect(() => {
    close()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [pathname])

  useEffect(() => {
    if (isOpen) inputRef.current?.focus()
  }, [isOpen])

  // Rendered after mount so the server markup stays platform-neutral.
  useEffect(() => {
    const isApplePlatform = /Mac|iPhone|iPad/.test(navigator.platform ?? "")
    setShortcutLabel(isApplePlatform ? "⌘ K" : "Ctrl K")
  }, [])

  // Cmd+K / Ctrl+K opens the search from anywhere.
  useEffect(() => {
    const onGlobalKeyDown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") {
        event.preventDefault()
        if (isOpen) {
          inputRef.current?.focus()
        } else {
          open()
        }
      }
    }
    window.addEventListener("keydown", onGlobalKeyDown)
    return () => window.removeEventListener("keydown", onGlobalKeyDown)
  }, [isOpen, open])

  // Close on Escape and on click outside.
  useEffect(() => {
    if (!isOpen) return
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") close()
    }
    const onPointerDown = (event: MouseEvent) => {
      if (rootRef.current && !rootRef.current.contains(event.target as Node)) {
        close()
      }
    }
    document.addEventListener("keydown", onKeyDown)
    document.addEventListener("mousedown", onPointerDown)
    return () => {
      document.removeEventListener("keydown", onKeyDown)
      document.removeEventListener("mousedown", onPointerDown)
    }
  }, [isOpen, close])

  // Full-text search as the visitor types.
  useEffect(() => {
    if (!isOpen) return
    const trimmed = query.trim()
    const seq = ++searchSeqRef.current
    if (!trimmed) {
      setHits([])
      setActiveIndex(0)
      return
    }
    ;(async () => {
      const pagefind = await loadPagefind()
      if (seq !== searchSeqRef.current) return
      if (!pagefind) {
        setHasIndex(false)
        return
      }
      const response = await pagefind.debouncedSearch(trimmed)
      if (!response || seq !== searchSeqRef.current) return
      const data = await Promise.all(
        response.results.slice(0, 6).map((result) => result.data()),
      )
      if (seq !== searchSeqRef.current) return
      setHits(
        data.map((item, index) => {
          const sub = pickAnchoredSubResult(item)
          return {
            id: `${index}-${item.url}`,
            url: normalizePagefindUrl(sub?.url ?? item.url),
            title: item.meta?.title || item.url,
            excerpt: sub?.excerpt || item.excerpt,
          }
        }),
      )
      setActiveIndex(-1)
    })()
  }, [query, isOpen])

  const askAi = useCallback(
    async () => {
      const trimmed = query.trim()
      if (!trimmed) return
      // Never interrupt an in-flight answer for the same query; retrying
      // after an error is allowed.
      if (askedQuery === trimmed && answerStatus === "streaming") return
      abortRef.current?.abort()
      const controller = new AbortController()
      abortRef.current = controller
      setAskedQuery(trimmed)
      setAnswer("")
      setAnswerStatus("streaming")
      try {
        const response = await fetch("/api/ai-search", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ query: trimmed }),
          signal: controller.signal,
        })
        if (response.status === 503) {
          setAnswerStatus("unconfigured")
          return
        }
        if (!response.ok || !response.body) {
          throw new Error(`Request failed with status ${response.status}`)
        }
        const reader = response.body.getReader()
        const decoder = new TextDecoder()
        let text = ""
        for (;;) {
          const { done, value } = await reader.read()
          if (done) break
          text += decoder.decode(value, { stream: true })
          setAnswer(text)
        }
        setAnswerStatus("done")
      } catch (error) {
        if ((error as Error).name === "AbortError") return
        setAnswerStatus("error")
      }
    },
    [query, askedQuery, answerStatus],
  )

  const onInputKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === "ArrowDown" || event.key === "ArrowUp") {
      if (hits.length === 0) return
      event.preventDefault()
      const delta = event.key === "ArrowDown" ? 1 : -1
      setActiveIndex((index) => {
        const next = index + delta
        if (next < -1) return hits.length - 1
        if (next >= hits.length) return -1
        return next
      })
      return
    }
    if (event.key === "Enter") {
      event.preventDefault()
      const hit = activeIndex >= 0 ? hits[activeIndex] : null
      if (hit) {
        router.push(hit.url)
      } else {
        askAi()
      }
    }
  }

  const showPanel = isOpen && (query.trim().length > 0 || answerStatus !== "idle")

  // Lock page scroll behind the full-screen results view.
  useEffect(() => {
    if (!showPanel) return
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = "hidden"
    return () => {
      document.body.style.overflow = previousOverflow
    }
  }, [showPanel])

  // Unique site pages the answer cites inline, in order of first mention.
  const sources = useMemo(() => {
    const seen = new Map<string, string>()
    for (const match of answer.matchAll(/\[([^\]]+)\]\((\/[^)\s]*)\)/g)) {
      const [, label, href] = match
      if (!seen.has(href)) seen.set(href, label)
    }
    return [...seen.entries()]
  }, [answer])

  return (
    <div ref={rootRef} className="ai-search-root" data-open={isOpen || undefined}>
      <button
        type="button"
        className="ai-search-trigger"
        aria-label="Search with AI"
        aria-expanded={isOpen}
        aria-keyshortcuts="Meta+K Control+K"
        title="Search (⌘K)"
        onClick={() => (isOpen ? close() : open())}
      >
        <AiSearchGlyph className="ai-search-glyph" />
        {shortcutLabel ? (
          <kbd className="ai-search-trigger-kbd" aria-hidden>
            {shortcutLabel}
          </kbd>
        ) : null}
      </button>

      {isOpen ? (
        <div className="ai-search-bar" role="search">
          <AiSearchGlyph className="ai-search-glyph ai-search-bar-glyph" />
          <input
            ref={inputRef}
            type="text"
            value={query}
            onChange={(event) => {
              setQuery(event.target.value)
              resetAnswer()
            }}
            onKeyDown={onInputKeyDown}
            placeholder="Search or ask anything about Tiles"
            aria-label="Search or ask anything about Tiles"
            autoComplete="off"
            autoCorrect="off"
            spellCheck={false}
            className="ai-search-input"
          />
          {query.trim() ? (
            <button
              type="button"
              className="ai-search-submit"
              aria-label="Get AI answer"
              title="Get AI answer (Enter)"
              onClick={() => askAi()}
            >
              <svg viewBox="0 0 24 24" fill="none" className="ai-search-submit-glyph" aria-hidden>
                <path
                  d="M5 12 H19 M13 6 L19 12 L13 18"
                  stroke="currentColor"
                  strokeWidth="1.8"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </button>
          ) : null}
          <button
            type="button"
            className="ai-search-close"
            aria-label="Close search"
            onClick={close}
          >
            <svg viewBox="0 0 24 24" fill="none" className="ai-search-close-glyph" aria-hidden>
              <path
                d="M6 6 L18 18 M18 6 L6 18"
                stroke="currentColor"
                strokeWidth="1.8"
                strokeLinecap="round"
              />
            </svg>
          </button>
          <span className="ai-search-hairline" aria-hidden />
        </div>
      ) : null}

      {showPanel ? (
        <div className="ai-search-panel">
          <div className="ai-search-panel-inner">
          {answerStatus === "idle" && query.trim() ? (
            <button type="button" className="ai-search-ask-hint" onClick={() => askAi()}>
              <AiSearchGlyph className="ai-search-glyph ai-search-answer-glyph" />
              <span className="ai-search-hint-desktop">
                Press{" "}
                <kbd aria-label="Enter">
                  <svg viewBox="0 0 24 24" fill="none" aria-hidden>
                    <path
                      d="M20 5 V11 A3 3 0 0 1 17 14 H5 M9 10 L5 14 L9 18"
                      stroke="currentColor"
                      strokeWidth="1.8"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </kbd>{" "}
                for an AI answer
              </span>
              <span className="ai-search-hint-mobile">
                Tap{" "}
                <span className="ai-search-hint-arrow" aria-label="the arrow button">
                  <svg viewBox="0 0 24 24" fill="none" aria-hidden>
                    <path
                      d="M5 12 H19 M13 6 L19 12 L13 18"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    />
                  </svg>
                </span>{" "}
                for an AI answer
              </span>
            </button>
          ) : null}
          {answerStatus !== "idle" ? (
          <div className="ai-search-answer">
            <div className="ai-search-answer-label">
              <AiSearchGlyph className="ai-search-glyph ai-search-answer-glyph" />
              <span>AI answer</span>
            </div>
            {answerStatus === "error" ? (
              <p className="ai-search-answer-note">
                Something went wrong. Try asking again.
              </p>
            ) : answerStatus === "unconfigured" ? (
              <p className="ai-search-answer-note">
                AI answers are not configured on this deployment yet.
              </p>
            ) : (
              <div className="ai-search-answer-body">
                {answer ? (
                  <ReactMarkdown>{answer}</ReactMarkdown>
                ) : (
                  <p className="ai-search-answer-note">Thinking…</p>
                )}
              </div>
            )}
            {sources.length > 0 ? (
              <p className="ai-search-sources">
                <span className="ai-search-sources-label">Sources</span>
                {sources.map(([href, label]) => (
                  <Link key={href} href={href} className="ai-search-source-link">
                    <span className="ai-search-source-favicon" aria-hidden>
                      <img
                        src="/lighticon.png"
                        alt=""
                        className="ai-search-source-favicon-light"
                      />
                      <img
                        src="/grey.png"
                        alt=""
                        className="ai-search-source-favicon-dark"
                      />
                    </span>
                    <span className="ai-search-source-label">{label}</span>
                  </Link>
                ))}
              </p>
            ) : null}
          </div>
          ) : null}

          {hits.length > 0 ? (
            <>
            <p className="ai-search-section-label">Pages</p>
            <ul className="ai-search-results" role="listbox" aria-label="Search results">
              {hits.map((hit, index) => {
                const isActive = index === activeIndex
                return (
                  <li key={hit.id} role="option" aria-selected={isActive}>
                    <button
                      type="button"
                      className="ai-search-item"
                      data-active={isActive || undefined}
                      onMouseEnter={() => setActiveIndex(index)}
                      onMouseLeave={() => setActiveIndex(-1)}
                      onClick={() => router.push(hit.url)}
                    >
                      <span className="ai-search-hit-title">{hit.title}</span>
                      <span
                        className="ai-search-hit-excerpt"
                        dangerouslySetInnerHTML={{ __html: hit.excerpt }}
                      />
                    </button>
                  </li>
                )
              })}
            </ul>
            </>
          ) : query.trim() && hasIndex ? (
            <p className="ai-search-empty">No matching pages.</p>
          ) : null}
          </div>
        </div>
      ) : null}
    </div>
  )
}
